<?php

namespace Mintreu\LaravelPanel;

use Illuminate\Filesystem\Filesystem;
use Illuminate\Support\Facades\Blade;
use Illuminate\Support\Str;
use Livewire\Livewire;
use Mintreu\LaravelPanel\Http\Livewire\Dashboard;
use Mintreu\LaravelPanel\Http\Livewire\Navigation;
use Mintreu\LaravelPanel\Http\Livewire\Sidebar;
use Mintreu\LaravelPanel\View\PanelTheme;
use Spatie\LaravelPackageTools\Package;
use Spatie\LaravelPackageTools\PackageServiceProvider;
use Mintreu\LaravelPanel\Commands\LaravelPanelCommand;

class LaravelPanelServiceProvider extends PackageServiceProvider
{
    public function configurePackage(Package $package): void
    {
        /*
         * This class is a Package Service Provider
         *
         * More info: https://github.com/spatie/laravel-package-tools
         */
        $package
            ->name('laravel-panel')
            ->hasConfigFile()
            ->hasRoute('web')
            ->hasViews()
            ->hasMigration('create_laravel-panel_table')
            ->hasCommand(LaravelPanelCommand::class);
    }




    public function bootingPackage()
    {
        Blade::component('panel::theme', PanelTheme::class);
        Livewire::component('panel::dashboard',Dashboard::class);
        Livewire::component('panel::navigation',Navigation::class);
        Livewire::component('panel::sidebar',Sidebar::class);
        $this->hasBootableUserComponents();
        parent::bootingPackage(); // TODO: Change the autogenerated stub
    }

    public function hasBootableUserComponents()
    {
        $filesystem = app(Filesystem::class);

        $allPanels = $filesystem->directories(app_path('Panels'));
        $panelFileList=[];
        foreach ($allPanels as $panel)
        {
            $panelFileList [Str::replace(app_path('Panels').'\\','',$panel)] = $filesystem->allFiles($panel);
        }

       // dd($panelFileList);
    }



}
